---
- name: Install Apache
  package:
    name: apache2
    state: present

- name: Configurating
  template:
    src: ../templates/index.html.j2
    dest: /var/www/html/index.html
  notify:
    - Restart Apache

- name: Checking conf
  copy:
    src: ../files/apache2.conf
    dest: /etc/apache2/apache2.conf
  notify:
    - Restart Apache

- name: Start and enable apache2 service
  service:
    name: apache2
    state: started
    enabled: yes



